# Generated by Django 4.2.6 on 2023-11-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_bankclients'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('secondName', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestRegist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=20)),
                ('code', models.IntegerField()),
                ('dateIn', models.CharField(max_length=20)),
                ('dateOut', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('worker', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InvestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('minTime', models.IntegerField()),
                ('minAmount', models.IntegerField()),
                ('code', models.CharField(max_length=20)),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MoneyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('course', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
